provider "google" {
  project = "tltestlab-project1" # The specific spoke project
}

# This block creates the connection for "Hop 1" (The "Hub"). 
# It uses the credentials provided by Terraform Cloud (OIDC) to authenticate as the Hub Service Account
provider "google" {
  alias = "impersonated"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/userinfo.email",
  ]
}

# This isn't a provider block, but a Data Source. 
# It uses the "Hub" provider (above) to request a token for the "Spoke" service account. 
# It effectively says: "Hey Hub, please get me a key for Spoke 1."
data "google_service_account_access_token" "default" {
  provider               = google
  target_service_account = "tfc-spoke-1@tltestlab-project1.iam.gserviceaccount.com"
  scopes                 = ["cloud-platform"]
  lifetime               = "3600s"
}

# The Resource Manager (The "Spoke")
# This is the default provider that the rest of my Terraform code will use. 
# It takes the token generated by the Bridge and uses it to manage the actual resources.
provider "google" {
  access_token = data.google_service_account_access_token.default.access_token
  project      = "tltestlab-project1"
}